variable "env_name" {}
variable "access_key" {}
variable "secret_key" {}
variable "region" {}
variable "availability_zone1" {}
variable "availability_zone2" {}
variable "nat_key_pair_name" {}
variable "ops_manager_ami" {}
variable "rds_db_name" {}
variable "rds_db_username" {}
variable "rds_db_password" {}
variable "rds_instance_class" {}
variable "rds_instance_count" {}
