#!/bin/bash -ex

RELEASE_DIR=$PWD/upstream-release
export VERSION=`cat version/number`

if [ "$USE_ERT_DUMMY" == "true" ]; then
  pushd p-runtime
    ./ci/scripts/helpers/bundle-gems.sh

    pushd ert-dummy
      cat ./metadata_parts/binaries.yml
      bundle exec vara build-pivotal --version=$VERSION .
    popd

  popd

  mv p-runtime/ert-dummy/*.pivotal ./ert.pivotal

else

  if [ "$EXTERNAL_RELEASE" != "" ]; then
    external_release_metadata="$PWD/$EXTERNAL_RELEASE"
  fi

  if [ $DERIVE_METADATA ]; then
    RELEASE_VERSION=`cat $RELEASE_DIR/version`
    TARBALL_FILENAME=$RELEASE_DIR/$RELEASE_NAME-$RELEASE_VERSION.tgz
    TARBALL_MD5=`md5sum $RELEASES_DIR/$TARBALL_FILENAME | awk '{ print $1 }'`

    cat > $PWD/p-runtime/metadata_parts/binaries.yml <<EOF
---
name: cf-autoscaling
releases:
  - file: $TARBALL_FILENAME
    name: $RELEASE_NAME
    version: $RELEASE_VERSION
    md5: $TARBALL_MD5
    url: $RELEASE_URL
EOF
  fi

  pushd p-runtime
    ./ci/scripts/helpers/bundle-gems.sh

    cat ./metadata_parts/binaries.yml
    bundle exec vara build-pivotal . --version=$VERSION --external-releases=$external_release_metadata

    # concourse streams working directory between containers
    # this won't be needed soon (#94235474, #93927268)
    rm releases/*.tgz
  popd

  mv p-runtime/*.pivotal ./ert.pivotal
fi
