#!/bin/bash -ex

RELEASE_DIR=$PWD/upstream-release
export VERSION=`cat version/number`

if [ "$USE_ERT_DUMMY" == "true" ]; then
  pushd p-runtime
    ./ci/scripts/helpers/bundle-gems.sh

    pushd ert-dummy
      cat ./metadata_parts/binaries.yml
      bundle exec vara build-pivotal --version=$VERSION .
    popd

  popd

  mv p-runtime/ert-dummy/*.pivotal ./ert.pivotal

else

  if [ "$EXTERNAL_RELEASE" != "" ]; then
    external_release_metadata="$PWD/$EXTERNAL_RELEASE"
  fi

  if [ $DERIVE_METADATA ]; then
    RELEASE_VERSION=`cat $RELEASE_DIR/version`
    TARBALL_FILENAME=$RELEASE_NAME-$RELEASE_VERSION.tgz
    github_api="https://api.github.com/repos/$GITHUB_RELEASE_ORG/$GITHUB_RELEASE_REPO"
    asset_id=`curl -u $GITHUB_USER_NAME:$GITHUB_ACCESS_TOKEN $github_api/releases/latest | jq '.assets[0].id'`

    curl -u $GITHUB_USER_NAME:$GITHUB_ACCESS_TOKEN -H "Accept:application/octet-stream" $github_api/releases/assets/$asset_id -L > p-runtime/releases/$TARBALL_FILENAME

    TARBALL_MD5=`md5sum p-runtime/releases/$TARBALL_FILENAME | awk '{ print $1 }'`

    cat > $external_release_metadata <<EOF
file: $TARBALL_FILENAME
name: $RELEASE_NAME
version: $RELEASE_VERSION
md5: $TARBALL_MD5
url: ""
EOF
  fi

  pushd p-runtime
    ./ci/scripts/helpers/bundle-gems.sh

    cat ./metadata_parts/binaries.yml
    bundle exec vara build-pivotal . --version=$VERSION --external-releases=$external_release_metadata

    # concourse streams working directory between containers
    # this won't be needed soon (#94235474, #93927268)
    rm releases/*.tgz
  popd

  mv p-runtime/*.pivotal ./ert.pivotal
fi
