#!/bin/bash -exu

SHA=$(shasum $file_to_hash | cut -d ' ' -f1)

echo -e "New ERT Pivotal file" > $output_subject_file
echo -e "The SHA1 hash of \"$file_to_hash\" is $SHA\n\nCheers!\n" > $output_body_file
