#!/bin/bash

set -ex

export RELENG_ENV=`cat environment/name`

pushd p-runtime
  ./ci/scripts/helpers/bundle-gems.sh

  xvfb-run -a bundle exec rake ert:configure_multi_az_instance_counts[$RELENG_ENV,$ERT_VERSION,$OPSMAN_VERSION]
popd
