#!/bin/bash

set -ex

export CF_VERSION=`cat bosh-io-cf/version`
export CF_MD5=`md5sum bosh-io-cf/release.tgz | awk '{ print $1 }'`
export CF_URL=`cat bosh-io-cf/url`

echo "---
- file: cf-$CF_VERSION.tgz
  name: cf
  version: '$CF_VERSION'
  md5: $CF_MD5
  url: $CF_URL" > cf-metadata.yml


export DIEGO_VERSION=`curl https://github.com/cloudfoundry/cf-release/releases/tag/v$CF_VERSION \
  | grep "Diego final release" \
  | sed -n 's/.*\([0-9]\.[0-9]\{4\}\.[0-9]\).*/\1/p' \
  | tr -d '\r\n'`

export DIEGO_URL=https://bosh.io/releases/github.com/cloudfoundry-incubator/diego-release?version=$DIEGO_VERSION

wget $DIEGO_URL -O diego-$DIEGO_VERSION.tgz

export DIEGO_MD5=`md5sum diego-$DIEGO_VERSION.tgz | awk '{ print $1 }'`
echo "---
- file: diego-$CF_VERSION.tgz
  name: diego
  version: '$DIEGO_VERSION'
  md5: $DIEGO_MD5
  url: $DIEGO_URL" > diego-metadata.yml
