#!/bin/bash

set -ex

export RELENG_ENV=`cat environment/name`

pushd p-runtime
  ./ci/scripts/helpers/bundle-gems.sh

  bundle exec rake opsmgr:download[aws,stable]
  bundle exec rake opsmgr:install[$RELENG_ENV,ops_man_image]
popd
