#!/bin/bash

set -ex

export RELENG_ENV=`cat aws-environments/name`
export OPS_MAN_PATH=$PWD/latest-opsman/ops_man_image


pushd p-runtime
  ./ci/scripts/helpers/bundle-gems.sh

  bundle exec rake opsmgr:install[$RELENG_ENV,$OPS_MAN_PATH]
popd
