#!/bin/bash

set -ex

export RELENG_ENV=`cat aws-environments/name`

pushd p-runtime
  ./ci/scripts/helpers/bundle-gems.sh

  xvfb-run -a bundle exec rake opsmgr:trigger_install[$RELENG_ENV,$OPSMAN_VERSION,45]
popd

