#!/bin/bash

set -ex

export RELENG_ENV=`cat aws-environments/name`
export INSTALLATION_PATH=$PWD/export-installation/installation.zip

pushd p-runtime
  ./ci/scripts/helpers/bundle-gems.sh

  xvfb-run -a bundle exec rake opsmgr:import_installation[$RELENG_ENV,$OPSMAN_VERSION,$INSTALLATION_PATH]
popd
