#!/bin/bash

set -ex

export RELENG_ENV=`cat environment/name`
export STEMCELL_PATH=$PWD/stemcell/*bosh-stemcell-*.tgz

pushd p-runtime
  ./ci/scripts/helpers/bundle-gems.sh

  xvfb-run -a bundle exec rake opsmgr:product:import_stemcell[$RELENG_ENV,$OPSMAN_VERSION,$STEMCELL_PATH,$PRODUCT_NAME]
popd

