#!/bin/bash

cat << EOF > json_body
{
"text": "Pipeline Passed! $PIPELINE_NAME\nJob: $JOB_NAME",
"username": "cheerleader", "icon_emoji": ":thumbsup:"
}
EOF

JSON_BODY=`cat json_body`
curl -X POST --data-urlencode "payload=$JSON_BODY" https://hooks.slack.com/services/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
