#!/bin/bash

set -ex

export RELENG_ENV=`cat environment/name`
export PIVOTAL_PATH=$PWD/ert-product/cf-*.pivotal

pushd p-runtime
  ./ci/scripts/helpers/bundle-gems.sh

  xvfb-run -a rake opsmgr:product:upload_add[$RELENG_ENV,$OPSMAN_VERSION,$PIVOTAL_PATH,cf]
popd
