---
name: database
label: Database
resource_label: Database
description: Database

templates:
{{if eq tile "srt"}}
- $( job "bpm" )
- $( job "loggregator_agent_mysql" )
- $( job "loggr-syslog-agent" )
- $( job "metrics-discovery-registrar" )
- $( job "metrics-agent" )
- $( job "loggr-forwarder-agent-mysql" )
- $( job "prom_scraper" )
- $( job "syslog_forwarder" )
- $( job "nats" )
- $( job "route_registrar_mysql_proxy" )
- $( job "proxy" )
- $( job "pxc-mysql" )
- $( job "galera-agent" )
- $( job "cluster-health-logger" )
- $( job "gra-log-purger" )
- $( job "mysql-metrics" )
- $( job "send-email" )
- $( job "mysql-diag-agent" )
{{else}}
- $( job "placeholder" )
{{end}}

resource_definitions:
- name: cpu
  type: integer
  label: CPU
  configurable: true
  default: 2
  constraints:
    min: 1

- name: ram
  type: integer
  label: RAM
  configurable: true
  default: 8192
  constraints:
    min: 4096

- name: ephemeral_disk
  type: integer
  label: Ephemeral Disk
  configurable: true
  default: 30000
  constraints:
    min: 10000

- name: persistent_disk
  type: integer
  label: Persistent Disk
  configurable: true
  default: 100000
  constraints:
    min: 10000

max_in_flight: 1
single_az_only: false
serial: true

instance_definition:
  name: instances
  type: integer
  label: Instances
  configurable: $( variable "database_configurable_state" )
  default: $( variable "database_default_instances" )
  constraints:
    min: $( variable "database_min_instances" )
    may_only_be_odd_or_zero: true
