---
name: database
label: Database
resource_label: Database
description: Database

templates:
{{ define "ert-database-templates" }}
- placeholder
{{ end }}
{{ define "srt-database-templates" }}
- consul_server
- metron_agent
- syslog_forwarder
- nats
- route_registrar_mysql_proxy
- proxy
- mysql
- mysql-metrics
- streaming-mysql-backup-tool
- send-email
- mysql-diag-agent
- mysql-restore
{{ end }}
{{ tile | ert_template "ert-database-templates" | srt_template "srt-database-templates" }}

resource_definitions:
- name: cpu
  type: integer
  label: CPU
  configurable: true
  default: 2
  constraints:
    min: 1

- name: ram
  type: integer
  label: RAM
  configurable: true
  default: 8192
  constraints:
    min: 4096

- name: ephemeral_disk
  type: integer
  label: Ephemeral Disk
  configurable: true
  default: 30000
  constraints:
    min: 10000

- name: persistent_disk
  type: integer
  label: Persistent Disk
  configurable: true
  default: 100000
  constraints:
    min: 10000

static_ip: 1
dynamic_ip: 0
max_in_flight: 1
single_az_only: false
serial: true

instance_definition:
  name: instances
  type: integer
  label: Instances
  configurable: {{ tile | ert "false" | srt "true" }}
  default: {{ tile | ert "0" | srt "1" }}
  constraints:
    min: {{ tile | ert "0" | srt "1" }}
    may_only_be_odd_or_zero: true
